### ISSUE TITLE
web页面标签修改问题

### ISSUE THREAD

**Issue by RogerHuOut** [n9e/fe-v5#10]
https://github.com/didi/nightingale/issues/788#issue-983615064
1.之前提交的该issue,替换提供的pub文件之后,告警策略页面空白的问题已经解决,但是原始提交的问题问题还存在
![image](https://user-images.githubusercontent.com/41337455/131837963-50fc4c12-29af-4e26-aac9-9284cd90008e.png)

2.滚动条消失
![image](https://user-images.githubusercontent.com/41337455/131837878-7a07e87c-da06-4ff5-b1aa-4bbc54fc87ac.png)

3.修改已有的告警策略,更换标签过滤条件,标签值无法选择,展示为空
![image](https://user-images.githubusercontent.com/41337455/131838275-563f1763-c671-4af5-ae17-2b7d7fab9229.png)

**Comment by guguji5** [comment]
@RogerHuOut 1.3 是同样的问题，麻烦再 `wget 116.85.64.82/pub.zip`更新一下吧。2 是预期行为，ant design的组件默认行为，没做修改

**Comment by RogerHuOut** [comment]
感谢，问题已解决
