### ISSUE TITLE
在设置标签时焦点离开再返回后可以继续编辑标签

### ISSUE THREAD

**Issue by singohgod** [n9e/fe-v5#100]
![1648607175987_6DAD3EE2-AC37-4101-9410-764593B19392](https://user-images.githubusercontent.com/252977/160740130-e893c2f1-2fe6-415c-b7bf-1d3a315f8ba9.png)

在输入标签的时候,一旦焦点离开,标签就不能修改了,但往往都会切出去拷贝ip机器名称什么的
必须一次性输入正确,否则就要删掉重来

建议焦点返回后恢复到可以继续编辑的状态

**Comment by guguji5** [comment]
回车，空格 或失去焦点时分词是为了更好的规范输入格式
