### ISSUE TITLE
时间范围记录最后一次选择的时间范围

### ISSUE THREAD

**Issue by singohgod** [n9e/fe-v5#101]
![1645601133950_03C7D5C8-CFE7-4d48-8A4C-4F4D949DA49E](https://user-images.githubusercontent.com/252977/160740545-5ca369b9-ab73-4990-b024-926b22f031b6.png)

**Comment by guguji5** [comment]
@singohgod 缓存了该时间选择器 左侧一栏的相对时间，右侧的绝对时间暂时没想到什么情况下需要缓存。
