### ISSUE TITLE
前端版本5.1.7监控大盘数据查看问题

### ISSUE THREAD

**Issue by RogerHuOut** [n9e/fe-v5#103]
前端版本5.1.7图表貌似有一点小问题：
1.计算inode使用率，换成百分比的计算方式稍作修改；
![1649135810(1)](https://user-images.githubusercontent.com/41337455/161684830-9ef47749-3ada-4ba7-a1ab-4c8615092960.jpg)

2.移动光标，数值不变见下图(磁盘使用率和inode使用率，貌似都有这个问题)
![1649136217(1)](https://user-images.githubusercontent.com/41337455/161684855-d4ebf9ad-32d7-4d35-a9c4-82cde0baaa81.jpg)

**Comment by jsers** [comment]
可以尝试在高级配置里面把小数点设置大一些，应该就能看到变化了

Roger_Hu ***@***.***> 于2022年4月5日周二 13:30写道：

**Comment by RogerHuOut** [comment]
第二个问题貌似是这个问题

**Comment by jsers** [comment]
问题一没太明白问题点是什么，关于百分比现在单位是支持 0-100 和 0-0.1 的两种方式

Roger_Hu ***@***.***> 于2022年4月6日周三 16:27写道：
