### ISSUE TITLE
5.1.7监控大盘优化建议

### ISSUE THREAD

**Issue by bbaobelief** [n9e/fe-v5#104]
前端版本：5.1.7
后端版本：5.5.0

1.默认按当前业务组添加busigroup变量，可以只在编辑的时候显示，看图页面不显示。这样做可以方便配置监控看板
![image](https://user-images.githubusercontent.com/3918461/161911549-06d83301-d80a-492c-b502-6b61ed839c38.png)

2.指标值 类型希望可以自定义颜色，尝试过 值映射 可以改变颜色，但要定义范围有点麻烦。
![image](https://user-images.githubusercontent.com/3918461/161912222-13250a59-cab9-4d69-b1e7-e28dd5122979.png)

3.建议：值映射 按格式化后的值生效，比如这个内存实际值是33566855168，如果按实际值配置范围映射会比较麻烦。
![image](https://user-images.githubusercontent.com/3918461/161912770-ffc7da4d-a4e1-43f2-8e8d-a382b42fdc1d.png)

4.变量展示超限
![image](https://user-images.githubusercontent.com/3918461/161953450-be838ad9-022e-4f0f-9cb5-2eec0c95cc12.png)

**Comment by jsers** [comment]
@bbaobelief 
问题2：目前暂时不支持自定义颜色，值映射主要是给满足某些条件后增加或区分视觉效果，未来会考虑是否支持自定义某个 serie 的颜色，或是支持选择一整个颜色方案

问题3: 如果按照建议的方式会带来问题，比如值小于 1000 的情况（虽然可以基于单位去做一些判断，但是这样设计就太复杂了）这里虽然配置的时候比较麻烦，但是一般情况配置完就不需要反复调整了，像内存和磁盘这类界限值其实都是比较固定的，自己换算下即可

**Comment by bbaobelief** [comment]
@jsers 明白，辛苦了。问题1可以实现吗。

**Comment by UlricQin** [comment]
需求1不是个通用做法，不予支持
