### ISSUE TITLE
当一台修改过时间(时间不正确)的机器上报后,会导致时序错乱,影响到很多正常监控的机器无法查看

### ISSUE THREAD

**Issue by singohgod** [n9e/fe-v5#106]
有些服务器因为业务需要会更改服务器的时间,比如测试一些商业化活动配置,如五一节活动,看看功能是否能正常进行,但当修改时间后,上报的到普罗米修斯的时序就出问题了,会导致之前很多正常上报的机器都看不到了

**Comment by UlricQin** [comment]
试试最新的 5.6.0 版本

**Comment by singohgod** [comment]
最近升级到5.6.2版本后,发现这个问题已经解决了~点赞~
