### ISSUE TITLE
监控大盘变量无限刷新

### ISSUE THREAD

**Issue by bbaobelief** [n9e/fe-v5#107]
**夜莺版本**:
前端版本：5.2.0
后端版本：5.6.0

**问题和复现方法**:
如果切换busigroup变量，ident变量选择框无限自动刷新。
```
busigroup  变量值 ops.deploy,ops.monitor
ident 变量值 label_values(system_uptime{busigroup="$busigroup"},ident)
```
![image](https://user-images.githubusercontent.com/3918461/163154983-d8637561-15ec-4a72-8776-561a336bdc78.png)

![QQ20220413-175931-HD](https://user-images.githubusercontent.com/3918461/163154352-78afe1ed-145f-4e0f-9427-8d581d238a84.gif)

**Comment by bbaobelief** [comment]
强制清理缓存之后，未在复现。

**Comment by guguji5** [comment]
@bbaobelief 尽管你没有复现，开启定时刷新后，大盘变量不应该刷新，我改下会更完备，感谢🙏
