### ISSUE TITLE
首次打开活跃告警不能显示

### ISSUE THREAD

**Issue by bbaobelief** [n9e/fe-v5#108]
前端版本：5.2.0
后端版本：5.6.0

新打开或者刷新 **活跃告警**，右侧为空，**必须切换** 聚合规则才能正常显示。

![QQ20220414-141811-HD](https://user-images.githubusercontent.com/3918461/163325468-82c5cf00-3adb-45f1-9193-49731291f156.gif)

**Comment by guguji5** [comment]
https://github.com/n9e/fe-v5/releases 已修改
