### ISSUE TITLE
无法屏蔽告警

### ISSUE THREAD

**Issue by bbaobelief** [n9e/fe-v5#109]
**夜莺版本**:
前端版本：5.2.0
后端版本：5.6.0

**问题和复现方法**:

屏蔽告警报错，猜测是id传的有问题

![image](https://user-images.githubusercontent.com/3918461/163327597-5f34294b-1b4a-418b-9798-f872ae601d66.png)

![image](https://user-images.githubusercontent.com/3918461/163327517-8807baa1-65ac-424f-9319-e6cd9a53fa38.png)

**Comment by guguji5** [comment]
怎么个复现步骤？

**Comment by bbaobelief** [comment]
@guguji5  从告警详情里随便点个，进行屏蔽的时候就会报错。

**Comment by guguji5** [comment]
活跃告警还是历史告警？我试了试没有出现，是不是因为 https://github.com/n9e/fe-v5/issues/108 这个问题导致的，现在最新的是5.2.1 可以先升级一下试试，如果还有问题，最好提供个详细步骤

**Comment by bbaobelief** [comment]
升级5.2.1版解决了
