### ISSUE TITLE
web能够展示离线资源数量和详情

### ISSUE THREAD

**Issue by RogerHuOut** [n9e/fe-v5#11]
需求描述：
工作台能够添加离线资源的数量，点击之后，能够查看那些资源是离线的状态

需求原因:
1.当前对于离线资源无感知；
2.当资源数量很多是，不容易查询出那些资源是处于离线状态的

**Comment by UlricQin** [comment]
这个需求收到，可能会在后面的版本放进去，目前可以用blackbox_exporter对机器做黑盒监控，agentd本身用systemd或supervisor托管保活

**Comment by UlricQin** [comment]
新版本5.0.0-ga已经支持target_up指标做设备离线告警，可以试试 https://github.com/didi/nightingale/releases/tag/v5.0.0-ga-06
