### ISSUE TITLE
功能缺失，建议新增

### ISSUE THREAD

**Issue by alangong114** [n9e/fe-v5#111]
# 建议开源版本新增如下功能
## 版本:
前端版本：5.2.0
后端版本：5.6.0

### 需求级别：P０
UI建议：
![image](https://user-images.githubusercontent.com/4981060/163550515-b2c2a4c5-3805-4628-8291-ef5c65921aaa.png)

５.６版本监控对ident无依赖，告警配置中对ident有依赖
<img width="685" alt="1650011704172_91AA2A29-45E1-412b-A124-E07DE61C90F5" src="https://user-images.githubusercontent.com/4981060/163550270-a8e56973-18b2-4064-97e2-542e5bd08a85.png">

功能描述：通过pull模式写入TSDB的ident对象，需要手工插mysql，target表，对开发不友好。

### 需求级别：P１
UI建议：
![image](https://user-images.githubusercontent.com/4981060/163548895-8d36cdd4-9c2c-471d-9e92-9419f0a72ac4.png)

功能描述：分享生成URL后，访问URL直接查看，无需登录鉴权。

### 需求级别：P２
![image](https://user-images.githubusercontent.com/4981060/163549100-aee3be9c-b576-4e44-a01d-49a0538ee18b.png)

功能描述：时间过长的历史告警，通过页面批量删除，不需要经过DB清洗，方便管理。

### 需求级别：P２

功能描述：对拥有写权限的用户，修改夜莺配置，进行用户行为审计功能

### 需求级别：P1
![image](https://user-images.githubusercontent.com/4981060/163558009-75af1f7b-cad6-4202-9f9f-e46928e80798.png)

功能描述：目前guest角色，没有所属团队的监控大盘，以及监控对象的查看能力，建议支持大盘的查看能力

## 总结
功能四如果开发工作量较大，可以考虑放到企业版本中

**Comment by jsers** [comment]
建议把这些点分开提，有些不单单是前端的改造，一些点可以提到夜莺主仓库里，这里先关闭了
