### ISSUE TITLE
输入框UI排版样式

### ISSUE THREAD

**Issue by qzhello** [n9e/fe-v5#114]
<img width="996" alt="image" src="https://user-images.githubusercontent.com/14229565/164579088-4dc37afa-4e57-42bc-af21-00cf7e9b2702.png">

原输入框如下：
<img width="717" alt="image" src="https://user-images.githubusercontent.com/14229565/164579307-5bfa03e3-b99c-4438-bc70-1b599b26370a.png">

问题描述：大盘中的下拉框如果数据过大，后面的变量会被遮住。
版本：v5.1.0

**Comment by guguji5** [comment]
@qzhello 最新版 应该fix了，，把pub使用最新版替换一下试试 https://github.com/n9e/fe-v5/releases

**Comment by qzhello** [comment]
已验证。
