### ISSUE TITLE
大盘表格示例

### ISSUE THREAD

**Issue by alangong114** [n9e/fe-v5#117]
## 期望：配置大盘表格
![image](https://user-images.githubusercontent.com/4981060/165876921-66b26ea1-8c1a-4db0-ba86-0c5dde5d6d05.png)

## 结果：
配置聚合参数时报错
![image](https://user-images.githubusercontent.com/4981060/165876981-4c5fb853-69c2-4e6b-bd0c-0930cad3da76.png)

希望能提供表格相关的配置示例

**Comment by jsers** [comment]
![image](https://user-images.githubusercontent.com/7424634/165894199-0cc1fa10-5ca6-400d-86f6-e12ce62c3b39.png)
