### ISSUE TITLE
监控大盘会支持grafana多查询类型吗？

### ISSUE THREAD

**Issue by chenginger** [n9e/fe-v5#118]
![image](https://user-images.githubusercontent.com/42002616/165881330-53520639-931c-42ef-9886-f28fcd2d9540.png)
监控大盘会支持类似grafana这种多查询类型吗？现在只能使用下拉选择体验不是很好

**Comment by UlricQin** [comment]
现在支持写query表达式，也支持写多个固定的值，逗号分隔，你的需求是什么，场景是什么












格雷厄姆
***@***.***

滴滴
高级专家工程师

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月29日(周五) 中午11:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [n9e/fe-v5] 监控大盘会支持grafana多查询类型吗？ (Issue #118)




 

 监控大盘会支持类似grafana这种多查询类型吗？现在只能使用下拉选择体验不是很好

**Comment by chenginger** [comment]
现在query或者，分割都是需要填写数据.然后呈现下拉的效果.我现在需要一个就是Text box的.自定义填写值.这样我就不需要每次有新的数据都要编辑这个变量.

还有个问题想提:
![image](https://user-images.githubusercontent.com/42002616/165882354-7578fcce-c0de-4efb-bc36-756bb81384a5.png)
我确定之后.试图就变为空了
![image](https://user-images.githubusercontent.com/42002616/165882375-40edea4e-a276-446e-8eae-f314c81e83b7.png)
我本地更新了最新版本代码了

**Comment by guguji5** [comment]
@chenginger 这个我们评估一下，看样子难度不大

**Comment by jsers** [comment]
@chenginger 
v5.7.0 支持 text box 类型了
