### ISSUE TITLE
大盘图标展示怎么没数据还会连接起来

### ISSUE THREAD

**Issue by chenginger** [n9e/fe-v5#123]
正常的Prometheus查询：
![image](https://user-images.githubusercontent.com/42002616/172598221-11e8c58f-a5e9-4cca-a86f-82d35a351e24.png)
使用夜莺的即时查询:
![image](https://user-images.githubusercontent.com/42002616/172598369-b12f9095-beb4-419e-ab16-e2919f2c7559.png)
这里导致查看图表的时候根本无法看出来是否未上报或者数据是否断层.监控大盘也是一样情况

**Comment by jsers** [comment]
@chenginger 
新版本已修复
https://github.com/n9e/fe-v5/releases/tag/v5.6.0

**Comment by chenginger** [comment]
![image](https://user-images.githubusercontent.com/42002616/187671922-73207fa7-508f-4185-b8ec-dc70e1d93e4e.png)
![image](https://user-images.githubusercontent.com/42002616/187672223-f31b18fd-b5ce-473e-929e-85e6cc982db4.png)

@jsers 新版本的好像又有这个问题

**Comment by jsers** [comment]
看截图没问题，只有 6:30 左右几分钟有数据
现在只会补中间的断点，前后的不会处理

chenginger ***@***.***> 于2022年8月31日周三 19:52写道：

**Comment by chenginger** [comment]
这样看起来有点别扭.很多人反馈以为有很多数据。为什么不做成和Prometheus这个一样呢@jsers

**Comment by jsers** [comment]
的确，下个版本处理下这个时间轴的 domain 问题

chenginger ***@***.***> 于2022年8月31日周三 19:58写道：
