### ISSUE TITLE
新建告警策略->修改了m的值，下面的提示没有变化

### ISSUE THREAD

**Issue by shook2012** [n9e/fe-v5#13]
策略类型  happen，版本v5 - rc7
![image](https://user-images.githubusercontent.com/8636757/132279512-a245a6aa-76eb-4846-b957-63138b8dd9a9.png)

**Comment by guguji5** [comment]
@shook2012 感谢反馈，修改了一下，可以 `wget 116.85.64.82/pub.zip` 更新一下前端pub 文件夹。

**Comment by shook2012** [comment]
多谢！
