### ISSUE TITLE
v5.6.0告警规则菜单双击两次显示初始化业务组

### ISSUE THREAD

**Issue by nondevops** [n9e/fe-v5#141]
v5.6.0告警规则菜单双击两次显示初始化业务组
![image](https://user-images.githubusercontent.com/12181410/177563584-9a074803-0618-42ff-9ae9-38fdad5c0f1a.png)
![image](https://user-images.githubusercontent.com/12181410/177563651-f0c73687-e32e-48a8-ad8b-4e46b2354b78.png)

**Comment by guguji5** [comment]
最新版应该好了。可以试试

**Comment by nondevops** [comment]
> 

最新版5.6.0问题依然存在
![image](https://user-images.githubusercontent.com/12181410/178753238-bc107d65-92fc-4563-bb22-23e21747f4b1.png)

**Comment by guguji5** [comment]
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/17986248/180992028-e00c4f0f-f2b9-4e15-9f83-63ebb78a2b3d.png">

commit（at 17:42）提晚了，最新版（at 11:21）里包含这次。可以再等等下个版本，或者把前端升级一下。

<img width="517" alt="image" src="https://user-images.githubusercontent.com/17986248/180992075-3e833644-452d-42c1-b773-a8307ede63f4.png">
