### ISSUE TITLE
快捷视图`展开维度标签`配置多个标签时，选中一个标签值，另一个标签选中的值会被重置

### ISSUE THREAD

**Issue by xiaoziv** [n9e/fe-v5#144]

**Comment by xiaoziv** [comment]
> @xiaoziv “展开维度标签” 是一个旧版本的设计了，建议先升级下

最新的master分支代码还是可以配置 “展开维度标签”
<img width="523" alt="image" src="https://user-images.githubusercontent.com/72858153/178760202-532685b9-34bf-424a-8e48-7a73cd9c6842.png">

**Comment by jsers** [comment]
v5.14.3 已修复
