### ISSUE TITLE
即时查询的几个使用感想

### ISSUE THREAD

**Issue by chenginger** [n9e/fe-v5#145]
1、夜莺默认开启Enable autocomplete.我们指标几百万默认提示好几次直接卡死.
2、下图这个球也是.指标多打开直接卡死浏览器.
![image](https://user-images.githubusercontent.com/42002616/178462075-3d13040d-17c0-444a-8d99-c356a67530e4.png)
3、建议能不能像Prometheus这个面板一样可以选择这些选项.感觉指标数据量比较多的话一些功能真的需要可以选择.如下图
![image](https://user-images.githubusercontent.com/42002616/178461687-80685823-b350-4183-b21e-ec3a752bd543.png)

**Comment by bbaobelief** [comment]
建议可以像falcon一样先搜索ident,然后过滤出机器，再输入metric过滤。
现在的即时查询对小白用户不够友好，如果lable比较多加上双引号很繁琐。
![image](https://user-images.githubusercontent.com/3918461/178647522-fffaa92e-dae5-449d-aa51-de4b14d240af.png)

试了快捷视图体验也不太好，默认会选中10个对象，如果指标很多清除重选就会被覆盖，且不能按lable搜索，只能按lable聚合。

**Comment by jsers** [comment]
@chenginger 收到，近期版本会带上 enable autocomplete 开关设置，以及 metrics 那个球的问题也会优化下
@bbaobelief 即使查询是需要对 promql 语法有一定的了解，后面会出一个弱化 promql 语法的选择器（两个模式可以切换）
快捷视图的问题不是很理解，label 的搜索是可以在“前置过滤条件”里面设置的

**Comment by jsers** [comment]
v5.8.0 已解决
