### ISSUE TITLE
监控大盘问题

### ISSUE THREAD

**Issue by chenginger** [n9e/fe-v5#150]
前端v5.6.0 后端v5.9.2
如果权限设置业务组是只读的话.点击分组下拉一直提示这个没有权限.很容易误操作
![image](https://user-images.githubusercontent.com/42002616/181152631-7eb2272f-28f2-423f-8b7d-79381c75dfb3.png)

**Comment by jsers** [comment]
@chenginger 
收到，这块涉及页面功能适配权限点，下个补丁版本会修复该问题

**Comment by jsers** [comment]
v5.8.0 已解决
