### ISSUE TITLE
5.7.1错误

### ISSUE THREAD

**Issue by chenginger** [n9e/fe-v5#155]
新增面板报错.time未初始化
![image](https://user-images.githubusercontent.com/42002616/181493378-d6c52edd-82d2-4b1a-b360-a8c73101faf9.png)

**Comment by jsers** [comment]
@chenginger 
麻烦提供下详细的复现步骤

**Comment by chenginger** [comment]
![image](https://user-images.githubusercontent.com/42002616/181499188-ee1391be-4573-4a2d-8f64-dc83ffc2bf7a.png)
@jsers 就新增啊

**Comment by jsers** [comment]
v5.8.0 已解决
