### ISSUE TITLE
监控大盘-问题反馈

### ISSUE THREAD

**Issue by bbaobelief** [n9e/fe-v5#157]
前端版本：5.7.2
后端版本：v5.10.0-ba0eafa065cf9cd9721c7aefe235500fccdaa941

1.这里的时间无法留空，点x 一直选中 最近1小时，会造成无法使用全局时间。
旧版本有个选择时间选型
![image](https://user-images.githubusercontent.com/3918461/182120094-74d59296-d13f-4663-a8b4-a1d9e8cf51bf.png)

![image](https://user-images.githubusercontent.com/3918461/182118731-adc9a2bd-dfb9-46a7-9bb5-ceb1d5beb453.png)

2.文字卡片无法使用深色模式
![image](https://user-images.githubusercontent.com/3918461/182121863-b5c53465-9602-4777-9d5a-d09f2a8f2fc8.png)

3.指标值-文字背景 颜色模式无法修改其他颜色且无法还原为白色
![image](https://user-images.githubusercontent.com/3918461/182123258-da776f23-6a78-4df5-a9b4-ed7d50fe977c.png)

**Comment by jsers** [comment]
@bbaobelief 
1. 应该是一个显示问题，关闭后就使用全局时间了
2. 文字卡片深色背景颜色需要自己去设置下
![image](https://user-images.githubusercontent.com/7424634/182145671-e6f63106-1587-4b3f-8885-b7658ff3e229.png)
3. 指标值控件颜色这块默认是基于一个色盘来根据序列数量来依次使用色盘里的颜色，如果需要设置颜色可考虑使用值映射（目前暂不支持单独给每个序列设置自定义的颜色）

**Comment by jsers** [comment]
问题1的显示问题，后面补丁版本我修复下

**Comment by jsers** [comment]
v5.8.0 已解决
