### ISSUE TITLE
监控大盘样式建议

### ISSUE THREAD

**Issue by JellyZero** [n9e/fe-v5#158]
1. 分组没有背景和边框看着很丑
现在：
![image](https://user-images.githubusercontent.com/109566229/182191956-a1493bb2-b3d0-4004-aea8-97881ee6ac19.png)
之前：
![image](https://user-images.githubusercontent.com/109566229/182192060-150a43fb-283c-4271-a6f4-9f1c49bdf65c.png)

![image](https://user-images.githubusercontent.com/109566229/182192210-dcba7eac-1452-400f-83d3-d5d6b78cfc21.png)
![image](https://user-images.githubusercontent.com/109566229/182192248-2242511c-3a3b-4d11-bf04-3c60bde063d1.png)

像上面这种操作区应该都要有背景色和边框颜色用于区分功能区

**Comment by JellyZero** [comment]
![image](https://user-images.githubusercontent.com/109566229/182197431-60a3b8ed-bd71-4559-9833-17db2dc3eb29.png)

这个切换到黑色兼容性不行,颜色都糊了

**Comment by JellyZero** [comment]
及时查询分享页面空白
![image](https://user-images.githubusercontent.com/109566229/182197574-06540652-4f02-4ddd-87b4-04eae38b9a0e.png)

![image](https://user-images.githubusercontent.com/109566229/182197692-1c6d49d3-72a7-45d8-bf31-5f0ca8c1ac3d.png)

**Comment by jsers** [comment]
设计的问题我们内部再讨论看下怎么处理
2 和 3 下个补丁版本修复

**Comment by JellyZero** [comment]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/109566229/182794621-07c2b3fd-4dcc-4df7-ba9e-3a794d08dc05.png">
这里歪了

**Comment by jsers** [comment]
v5.8.0 版本已解决
