### ISSUE TITLE
通过活跃报警跳转无法屏蔽报警

### ISSUE THREAD

**Issue by mxq0923** [n9e/fe-v5#159]
前端版本：5.7.2
    后端版本：v5.10.1-bb17751a81b12608c6f28d5c8c6e27ae91a7abaf

通过活跃报警跳转无法屏蔽报警，直接通过屏蔽规则创建，可以正常添加屏蔽规则。

控制台显示如图：
![图片](https://user-images.githubusercontent.com/12837605/182506403-7fc1ceb0-1b50-4512-b4d8-90f88e600955.png)

**Comment by mxq0923** [comment]
Firefox（104.0b5 (64 位)） 测试有这个问题，chrome 测试正常。

**Comment by jsers** [comment]
@mxq0923 
先尽量使用 Chrome 吧，Firefox 不作必要的测试
但是你这个 Firefox 的版本也挺奇怪的，现在最新版本是 103（并且我刚试了下 103.0.1 版本没问题），104 是一个 dev 版本吗？

**Comment by guguji5** [comment]
最新的代码已经fix
