### ISSUE TITLE
图表设置 PromQL 支持“新手模式”

### ISSUE THREAD

**Issue by jsers** [n9e/fe-v5#164]
对于不太熟悉 PromQL 语法的用户可以通过界面化交互来降低配置成本

**Comment by cdz620** [comment]
大佬咨询一下，
问题1：这个大概什么时候会实现?

**Comment by jsers** [comment]
@cdz620 多谢建议，大体上会参考 grafana 的设计，具体发布该功能的时间目前无法确定啊

**Comment by cdz620** [comment]
基于这个版本，已经实现如下功能
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/13965190/185597308-18d87491-78f1-4425-b43b-2c6a2e2b09f9.png">

**Comment by jsers** [comment]
👍🏻 “操作符” 这个应该是支持多个的，同时也得支持调整顺序，可能还有其他的场景，回头可以考虑提个 PR

cdz620 ***@***.***> 于2022年8月19日周五 18:14写道：

**Comment by jicki** [comment]
这个模式，大概什么时候会上线吗？

**Comment by beautytea8** [comment]
> @beautytea8 这个模式，大概会在那一个版本实现吗？

二开实现的，暂时没时间merge到开源版本

**Comment by jicki** [comment]
> > @beautytea8 这个模式，大概会在那一个版本实现吗？
> 
> 二开实现的，暂时没时间merge到开源版本
期待能早点 merge

**Comment by jsers** [comment]
@beautytea8 
现在可能不太好合并到主分支，可以有空提交个其他的 remote
后面我找时间合并进来

**Comment by jsers** [comment]
v5.15.0 已支持
