### ISSUE TITLE
【建议】填写飞书或其他协作平台token的时候，需要把url前面的部分删除掉，但是大部分用户会直接填写url，保存url后，会导致机器人发送告警失败

### ISSUE THREAD

**Issue by cdz620** [n9e/fe-v5#167]
如题

**Comment by UlricQin** [comment]
这个issue不应该是前端来做限制处理，因为前端其实不知道哪个字段代表的是token。对于扩展联系方式，每个字段都是配置文件配置出来的。所以前端不理解各个字段的语义。

这个需求，如果要提升兼容性，应该在feishu.go或dingtalk.go或wecom.go里具体做发送的时候，如果发现是http打头的，就直接使用用户填写的地址，不用在前面拼接baseurl了

**Comment by cdz620** [comment]
如果从定位成"扩展联系方式"出发，来确实没有必要加业务逻辑的判断，明白了。
希望后端能处理下这种情况，推广的时候，老是被问到这个问题。
