### ISSUE TITLE
【建议】集成eslint，提高代码质量

### ISSUE THREAD

**Issue by cdz620** [n9e/fe-v5#168]
希望前端代码集成eslint检测，目前发现未使用的import有部分遗留在代码里，会导致有些IDE用快捷键格式化代码的时候，会移除这些代码，导致本地分支与目前的项目差异较大，代码容易冲突
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/13965190/183840136-0f563ede-5718-4192-9ca8-5f601f08dae7.png">

推荐使用： https://pro.ant.design/zh-cn/docs/lint/

**Comment by jsers** [comment]
历史问题，目前无法一刀切集成 eslint，后面空闲时间了再整体处理这部分

cdz620 ***@***.***> 于2022年8月10日周三 15:27写道：

**Comment by jsers** [comment]
@cdz620 可以关闭 vscode 全局的 formatOnSave
