### ISSUE TITLE
【bug】屏蔽规则无法保存，"react_devtools_backend.js:4026 TypeError: e.cluster.join is not a function"

### ISSUE THREAD

**Issue by cdz620** [n9e/fe-v5#169]
## 操作步骤

活跃告警 -> 聚合卡片 -> 告警列表 -> 点击屏蔽 -> 跳转屏蔽设置页面，如下，-> 点击保存，报错。

<img width="2552" alt="image" src="https://user-images.githubusercontent.com/13965190/183842749-385f1873-bfa7-4f20-a242-ccddbbb6c406.png">

## 其他信息

但是如果重新选择一遍对应的集群，再保存，就不会报错。

**Comment by jsers** [comment]
最新版本已修复
