### ISSUE TITLE
订阅规则选择时支持多选

### ISSUE THREAD

**Issue by wsxedcer** [n9e/fe-v5#170]
前端版本：5.9.0
后端版本：v5.10.3-f18ed76593c27a40a6de5bbf9d4b733d62ec6c63

现在的通用报警规则是创建在一个公共业务组中，然后各个业务组通过订阅相关的规则发送报警，在创建订阅规则的时候每次只能选取一条，但是“订阅事件标签Key” 这个条件大部分情况下是一致的，希望能增加多选功能

**Comment by UlricQin** [comment]
目前没有计划，你可以对这些有共性的告警规则，统一附加一个相同的标签，比如dept=a，订阅规则里就可以根据这个标签做订阅
