### ISSUE TITLE
前端页面白屏

### ISSUE THREAD

**Issue by leozz705** [n9e/fe-v5#175]
出现在监控大盘：http探测相关（用categraf的http_response和prometheus的blackbox采集监控的域名）
展示部分域名监控的时候就会白屏：
前端版本：5.9.0
后端版本：v5.10.3
浏览器：edge
页面控制台报错如下：

![image](https://user-images.githubusercontent.com/78150430/185021605-895f39cc-0ecc-4ff9-8d4e-46c2cb684922.png)

**Comment by UlricQin** [comment]
1.用chrome浏览器
2.用的是内置的监控大盘，还是自己的做的，自己做的大盘的话贴一下promql

**Comment by leozz705** [comment]
1，edge也是谷歌的内核，再说我用了chrome也是一样。
2，用的两种数据采集（categraf的http_response和prometheus的blackbox）都试过了，用的内置监控大盘和grafana导过来的改版也是一样的报错。
仅是给不同项目环境的域名分了组而已，选到某些环境的域名就直接白屏了。
内置的加过条件区分；
grafana导入过来的也只是加了条件区分：
probe_http_status_code{project=~"$project",env=~"$env"} - 0
probe_duration_seconds{project=~"$project",env=~"$env"} - 0
(probe_ssl_earliest_cert_expiry{project=~"$project",env=~"$env"}-time())/3600/24

**Comment by leozz705** [comment]
刚添加k8s图的时候也遇到相同报错了，报错都是表格的

**Comment by UlricQin** [comment]
前端最新版本是 5.9.1，升级一下试试

**Comment by jsers** [comment]
@leozz705 
可以先升级下前端，如还有问题贴下大盘的 json

**Comment by leozz705** [comment]
早上就升级到5.9.1了

{
    "name": "证书监控",
    "tags": "",
    "configs": {
        "var": [
            {
                "type": "query",
                "name": "project",
                "definition": "label_values(probe_success,project)",
                "multi": true,
                "allOption": true
            },
            {
                "type": "query",
                "name": "env",
                "definition": "label_values(probe_success{project=~\"$project\"},env)",
                "multi": true,
                "allOption": true
            }
        ],
        "panels": [
            {
                "targets": [
                    {
                        "refId": "A",
                        "expr": "probe_success{project=~\"$project\",env=~\"$env\"} - 0",
                        "legend": "状态"
                    },
                    {
                        "expr": "probe_http_status_code{project=~\"$project\",env=~\"$env\"} - 0",
                        "refId": "B",
                        "legend": "状态码"
                    },
                    {
                        "expr": "probe_duration_seconds{project=~\"$project\",env=~\"$env\"} - 0",
                        "refId": "C",
                        "legend": "耗时(s)"
                    },
                    {
                        "expr": "(probe_ssl_earliest_cert_expiry{project=~\"$project\",env=~\"$env\"}-time())/3600/24",
                        "refId": "D",
                        "legend": "证书剩余天数"
                    }
                ],
                "name": "总览",
                "custom": {
                    "showHeader": true,
                    "colorMode": "value",
                    "calc": "lastNotNull",
                    "displayMode": "labelValuesToRows",
                    "aggrDimension": "instance"
                },
                "options": {
                    "standardOptions": {}
                },
                "overrides": [
                    {
                        "matcher": {
                            "value": "A"
                        },
                        "properties": {
                            "valueMappings": [
                                {
                                    "type": "special",
                                    "result": {
                                        "color": "#ff2222",
                                        "text": "DOWN"
                                    },
                                    "match": {
                                        "special": 0
                                    }
                                },
                                {
                                    "type": "special",
                                    "result": {
                                        "color": "#4fb35e",
                                        "text": "UP"
                                    },
                                    "match": {
                                        "special": 1
                                    }
                                }
                            ],
                            "standardOptions": {
                                "util": "none"
                            }
                        }
                    },
                    {
                        "type": "special",
                        "matcher": {
                            "value": "D"
                        },
                        "properties": {
                            "standardOptions": {
                                "util": "none",
                                "decimals": 0
                            }
                        }
                    }
                ],
                "version": "2.0.0",
                "type": "table",
                "layout": {
                    "h": 17,
                    "w": 24,
                    "x": 0,
                    "y": 0,
                    "i": "156eddb2-f65f-4670-92d5-b68958f1badf",
                    "isResizable": true
                },
                "id": "156eddb2-f65f-4670-92d5-b68958f1badf"
            }
        ],
        "version": "2.0.0"
    }
}

**Comment by leozz705** [comment]
{
    "name": "HTTP探测",
    "tags": "",
    "configs": {
        "version": "2.0.0",
        "panels": [
            {
                "id": "ea45df7c-056e-41cc-aa8f-bce51f5ff328",
                "type": "row",
                "name": "域名检测",
                "layout": {
                    "h": 1,
                    "w": 24,
                    "x": 0,
                    "y": 0,
                    "i": "ea45df7c-056e-41cc-aa8f-bce51f5ff328",
                    "isResizable": false
                },
                "collapsed": true,
                "panels": []
            },
            {
                "targets": [
                    {
                        "refId": "A",
                        "expr": "max(http_response_result_code{project=~\"$project\",environment=~\"$environment\"}) by (target)",
                        "legend": "状态"
                    },
                    {
                        "expr": "max(http_response_response_code{project=~\"$project\",environment=~\"$environment\"}) by (target)",
                        "refId": "B",
                        "legend": "状态码"
                    },
                    {
                        "expr": "max(http_response_response_time{project=~\"$project\",environment=~\"$environment\"}) by (target)",
                        "refId": "C",
                        "legend": "响应时间(s)"
                    },
                    {
                        "expr": "(max(http_response_cert_expire_timestamp{project=~\"$project\",environment=~\"$environment\"}) by (target) - time())/3600/24",
                        "refId": "D",
                        "legend": "证书（天）"
                    }
                ],
                "name": "URL Details",
                "custom": {
                    "showHeader": true,
                    "colorMode": "value",
                    "calc": "lastNotNull",
                    "displayMode": "labelValuesToRows",
                    "aggrDimension": "target"
                },
                "options": {
                    "valueMappings": [],
                    "standardOptions": {}
                },
                "overrides": [
                    {
                        "properties": {
                            "valueMappings": [
                                {
                                    "type": "special",
                                    "result": {
                                        "color": "#000000",
                                        "text": "UP"
                                    },
                                    "match": {
                                        "special": 0
                                    }
                                },
                                {
                                    "type": "special",
                                    "result": {
                                        "color": "#000000",
                                        "text": "DOWN"
                                    },
                                    "match": {
                                        "special": 1
                                    }
                                }
                            ],
                            "standardOptions": {}
                        },
                        "matcher": {
                            "value": "A"
                        }
                    },
                    {
                        "type": "special",
                        "matcher": {
                            "value": "D"
                        },
                        "properties": {
                            "standardOptions": {
                                "util": "none",
                                "decimals": 0
                            }
                        }
                    }
                ],
                "version": "2.0.0",
                "type": "table",
                "layout": {
                    "h": 15,
                    "w": 24,
                    "x": 0,
                    "y": 1,
                    "i": "fb316ecc-cc5d-4022-9657-39300096ca34",
                    "isResizable": true
                },
                "id": "fb316ecc-cc5d-4022-9657-39300096ca34"
            }
        ],
        "var": [
            {
                "definition": "label_values(http_response_result_code, project)",
                "name": "project"
            },
            {
                "definition": "label_values(http_response_result_code{project=~\"$project\"}, environment)",
                "name": "environment"
            }
        ]
    }
}
