### ISSUE TITLE
告警规则里的生效时间后端是支持开始时间大于结束时间，但前端选择时不支持

### ISSUE THREAD

**Issue by hel2o** [n9e/fe-v5#176]
前端在保存生效时间时如果结束时间小于开始时间则会自动调换两个时间，保存到后端依然是开始时间小于结束时间
对于有时候要排除一段时间范围不是很方便，后端已经支持开始时间大于结束时间，前端就不应该强制调换2个时间位置，建议取消选择时的强制调换位置功能。

**Comment by hel2o** [comment]
@jsers ，有空看看，怕我描述的不清楚，我录屏一遍
![动画](https://user-images.githubusercontent.com/14226648/187867475-638fcfd1-33bb-41b5-9e22-0d39453cee59.gif)

**Comment by jsers** [comment]
v5.11.1 版本已修复

**Comment by jsers** [comment]
之前描述没问题啊，现在的确是不可以的
下个版本会把这个“时间范围”拆成两个时间选择

hel2o ***@***.***> 于2022年9月1日周四 16:22写道：
