### ISSUE TITLE
bug: nightingle模式输入监控指标时需4个字符以上才发起检索，可能导致无法输入小于4个字符的指标

### ISSUE THREAD

**Issue by joyexpr** [n9e/fe-v5#18]
nightingle模式输入监控指标（如即时看图、监控大盘图表、告警策略指标等）时需4个字符以上才发起检索，可能导致无法输入小于4个字符的指标，如指标名为up的指标

**Comment by guguji5** [comment]
ga版本 已弃用nightingle模式
