### ISSUE TITLE
迁移grafana图标，不支持custom类型变量和label_values函数

### ISSUE THREAD

**Issue by icesharp132** [n9e/fe-v5#180]
<img width="686" alt="image" src="https://user-images.githubusercontent.com/5111350/186569754-13a0f731-a17c-484b-993d-b95a29c7034a.png">
grafana中有custom类型变量，迁移到夜莺后不支持
<img width="127" alt="image" src="https://user-images.githubusercontent.com/5111350/186569833-66efc925-6559-46d9-b0a8-24cabd9dbdf9.png">

另外grafana中内置label_values函数，导致用了label_values函数的看板在夜莺不显示

**Comment by UlricQin** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/2769466/186588434-40b22289-25d6-4420-8086-a5615bb739ee.png">
都是支持的，自定义的这种，就选择Query，然后多个value之间逗号分隔即可，@jsers 看看咱们是否把自定义的这种单独作为一个类型更直观

**Comment by jsers** [comment]
@icesharp132 
下个版本把 custom 类型加进去
大盘变量准备大改下，现在全部显示变量的设置项，以及无法承受多样化的变量的类型

**Comment by jsers** [comment]
v5.11.1 版本支持配置 custom 类型的变量
