### ISSUE TITLE
关于监控大盘中的蜂窝图需要修改的地方

### ISSUE THREAD

**Issue by jwh5566** [n9e/fe-v5#181]
![9aad1271a9354b299f1d3cc0f0895ec](https://user-images.githubusercontent.com/7205703/186651401-d9f854d6-2e91-4436-a33c-3d26eadcc19f.jpg)

蜂窝图显示数值，没有什么意义，正常情况下 我觉得只显示label就可以，用来标识不同的应用
值的话可以用颜色来区分正常或者异常的情况

**Comment by jsers** [comment]
好建议，后面加一个显示内容的选项

蒋文华 ***@***.***> 于2022年8月25日周四 19:30写道：

**Comment by jsers** [comment]
v5.11.1 版本添加可选择显示内容
