### ISSUE TITLE
即时查询，graph 的tab，点击execute不会重新查询数据，除非表达式变了，详情见截图

### ISSUE THREAD

**Issue by cdz620** [n9e/fe-v5#184]
<img width="2510" alt="image" src="https://user-images.githubusercontent.com/13965190/187328414-c754c6c2-7f1a-4875-aa6a-f9f6c82dab50.png">

**Comment by jsers** [comment]
的确有点问题，下个版本修复下

cdz620 ***@***.***> 于2022年8月30日周二 09:36写道：

**Comment by jsers** [comment]
v5.11.1 版本已修复
