### ISSUE TITLE
feature: 希望在输入promsql时，支持提示和autocomplete

### ISSUE THREAD

**Issue by joyexpr** [n9e/fe-v5#19]
目前在输入promsql没有任何提示，不大方便 ，希望能增加支持提示和autocomplete

**Comment by guguji5** [comment]
安排上了，指日可待

**Comment by guguji5** [comment]
@joyexpr 使用5.0.0-ga-01 以上版本 支持了promQl，自动闭合也有

**Comment by guguji5** [comment]
![suggestino3](https://user-images.githubusercontent.com/17986248/150276482-0f279f4c-b0c0-4d35-8cee-56263ed665b8.gif)
原来的自动闭合和suggestion有点问题，修复一下
