### ISSUE TITLE
快捷视图能否只展示当前条件下有的指标

### ISSUE THREAD

**Issue by icesharp132** [n9e/fe-v5#192]
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/5111350/189882756-e8c56c86-02f4-4e7f-a7ce-1392d3029214.png">
目前不管前置过滤条件怎么选，右侧监控指标里可选的是Prometheus中所有存在的指标，寻找指标很不方便
能否支持只显示当前选中的条件下存在的指标

**Comment by jsers** [comment]
前置过滤条件不是用来过来右侧的指标列表，需要过滤指标列表可以用列表上方的搜索

**Comment by icesharp132** [comment]
> 

嗯是可以用搜索，但是这样就要知道指标名称才可以，不是很易用

**Comment by jsers** [comment]
搜索是一个模糊搜索，只需要搜索你需要查询的指标关键词就行
你想要的是一个指标的前置过滤，这个目前是不支持的，和快捷视图目前的设计不太一样
目前的设计是满足用户可以设置好自定义的视角，目前这个视角是不包含过滤指标的
如果需要有个场景查看固定的指标，感觉你可以把这些指标配置到某个大盘里面是比较合适的方式

icesharp ***@***.***> 于2022年9月14日周三 17:49写道：
