### ISSUE TITLE
大盘条件配置中，“筛选正则”支持变量

### ISSUE THREAD

**Issue by icesharp132** [n9e/fe-v5#193]
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/5111350/189883608-71544728-b4ca-4bf7-ac78-f7082626f51b.png">
grafana中查询条件的“筛选正则”支持配置前面设置的变量，夜莺目前不支持

**Comment by jsers** [comment]
这个目前的确不支持，后面版本会加上
