### ISSUE TITLE
夜莺相对grafana消耗带宽较大（大约3倍）

### ISSUE THREAD

**Issue by icesharp132** [n9e/fe-v5#194]
同样的大盘，夜莺网络传输量为30M，grafana网络传输量为9M左右（多次测试），考虑优化下吗
夜莺：
<img width="634" alt="image" src="https://user-images.githubusercontent.com/5111350/189884460-f033cf62-1849-4800-a5b0-aeaf9b5da6c5.png">
grafana：
<img width="684" alt="image" src="https://user-images.githubusercontent.com/5111350/189885041-48f129e7-df92-4ca7-9027-87d7ff80792f.png">

**Comment by jsers** [comment]
可以再细节一点，目前这个对比没有太多意义，夜莺会有个 pure 的轮询状态接口，如果大盘长时间打开着，这个总体传输肯定会比较大。
可以对比下某个 query 的结果，理论上会有一定的优化空间，但是这点流量感觉真不是一个大问题，未来出移动版的时候倒是会注意下这个问题

**Comment by jsers** [comment]
可以再细节一点，目前这个对比没有太多意义，夜莺会有个 pure 的轮询状态接口，如果大盘长时间打开着，这个总体传输肯定会比较大。
可以对比下某个 query 的结果，理论上会有一定的优化空间，但是这点流量感觉真不是一个大问题，未来出移动版的时候倒是会注意下这个问题

**Comment by icesharp132** [comment]
这个是单次打开同一个大盘，展示了所有图表的情况
没有开启自动刷新，多次刷新测试表现非常稳定

**Comment by jsers** [comment]
pure 接口不是自动刷新，这是一个大盘状态的探测接口

icesharp ***@***.***> 于2022年9月14日周三 17:47写道：

**Comment by guguji5** [comment]
@icesharp132 grafana 会有前端和后端，启动后，后端对接数据源会帮承担一部分计算，聚合查询，批量存储的逻辑，而夜莺的前端相当于直连数据源（尽管过了夜莺后端，但是它只转发），所以前端发送的数据会多一些。不确定是不是这原因。
