### ISSUE TITLE
即时查询优化建议

### ISSUE THREAD

**Issue by bbaobelief** [n9e/fe-v5#198]
前端版本：5.11.1
后端版本：v5.11.3-23eb766c14c7021533b6b1b58e9b326bd9e4ef80
1.BUG：多集群 切换集群会导致输入框promQL被清空，有时好不容易写的语法，一切换就没了。
![image](https://user-images.githubusercontent.com/3918461/191459537-bed7a676-602a-4744-90c7-7dc4c19a1d7d.png)

~~2.BUG：即时查询有断点的线被连起来了，有误导性。~~ 新版已解决。
![image](https://user-images.githubusercontent.com/3918461/191462189-8039312b-6287-40d4-94ab-eaa8a2bb19be.png)
展示成这样比较准确
![image](https://user-images.githubusercontent.com/3918461/191462278-24b21fe4-e045-4432-bc2d-948b2db6c2e5.png)

~~3.BUG：Series显示不全~~ 新版已解决。
![image](https://user-images.githubusercontent.com/3918461/191463004-d50ea7da-3cfb-4618-ab51-94f55b64dc55.png)

4.Feat：支持通过url参数控制Table和Graph切换，需求是从告警详情点击可以直接看图。如果url可以传时间更好，未来想借助这个页面做成像grafana那样告警可以带上截图。
![image](https://user-images.githubusercontent.com/3918461/191458242-104ac08f-28ae-4a84-9151-a6716ea18727.png)
![image](https://user-images.githubusercontent.com/3918461/191458652-85b0db63-44e4-42fa-8cba-da021a4c99fe.png)

**Comment by jsers** [comment]
1. 暂时不太好改，后面全局集群交互可能会有比较大的优化到时候再整体看下怎么处理
2. v5.13.0 已处理
4. 改动有点大准备放到下个版本支持（我们版本更新很快的）
