### ISSUE TITLE
升级v5.13.0 监控大盘报错

### ISSUE THREAD

**Issue by bbaobelief** [n9e/fe-v5#204]
```
 {
      "multi" : true,
      "name" : "cluster",
      "type" : "custom",  // 以前的大盘没这个字段
      "definition" : "tx,ali,aws"
    }
```
新的大盘增加了 `"type" : "custom"` 字段，旧的大盘没这个type字段导致图表消失，需要处理下错误。
![image](https://user-images.githubusercontent.com/3918461/195528948-8e8b363e-02b2-4516-89ec-7719edcc851c.png)

**Comment by jsers** [comment]
把大盘 json ***@***.***
这个 type 很早之前的版本就已经加上了

zheng ***@***.***> 于2022年10月13日周四 15:25写道：

**Comment by jsers** [comment]
@bbaobelief 
https://github.com/n9e/fe-v5/releases/tag/v5.13.1
发了一个补丁版本
