### ISSUE TITLE
v5.13.0分享功能提示无操作权限

### ISSUE THREAD

**Issue by chenginger** [n9e/fe-v5#205]
![image](https://user-images.githubusercontent.com/42002616/195750542-e6c7bc5e-f0ca-4425-8eb1-bd1b2d63c460.png)
分享后的视图点击分组一直提示无操作权限.让人比较困惑

**Comment by UlricQin** [comment]
配置文件里开启了匿名访问了么，贴 webapi.conf

**Comment by jsers** [comment]
分组展开和关闭的确会触发更新接口，这个我修复下
