### ISSUE TITLE
vite-plugin-react-svg缺陷

### ISSUE THREAD

**Issue by zhangtinghang** [n9e/fe-v5#206]
在fe-v5的5.13.2版本对引入的vite-plugin-react-svg@0.2.0，针对内部isBuild为true的情况下，将报错path is not defined。
![image](https://user-images.githubusercontent.com/21197164/196868996-ac3cc80d-ad7b-4d5e-ac7f-5d8940a3f05c.png)

**Comment by guguji5** [comment]
@zhangtinghang @tripitakav  本地有change吗？package-lock 应该没删除吧

**Comment by zhangtinghang** [comment]
@guguji5 @tripitakav 我试了下，是因为升级的时候package.json文件的react大版本调整了，isBuild的参数改成对象了，需要回退下package.json文件的react版本，重新安装依赖即可，本地测试有效。

**Comment by JellyZero** [comment]
这个问题一直都有问题

**Comment by guguji5** [comment]
@JellyZero @tripitakav 可以参考 @zhangtinghang 回答。如果你升级react大版本要把依赖自己处理好
