### ISSUE TITLE
建议监控大盘也能按分组展示

### ISSUE THREAD

**Issue by bbaobelief** [n9e/fe-v5#21]
如题，左侧增加分组：
![image](https://user-images.githubusercontent.com/3918461/133601129-12a0a495-1ba5-4f77-95b5-583d19070424.png)
![image](https://user-images.githubusercontent.com/3918461/133601289-be12bc3b-d1bc-4745-9555-72e5b9d7cb08.png)

**Comment by UlricQin** [comment]
后面可能会重新设计v5，让大盘也支持分组
