### ISSUE TITLE
tagv5.3.0大屏上移下移对chrome和firefox浏览器相反，以及中间删除会导致移动失败

### ISSUE THREAD

**Issue by wjyzhixing** [n9e/fe-v5#213]
<img width="676" alt="image" src="https://user-images.githubusercontent.com/36620969/202330732-57a546e0-82db-4f58-afef-a8153fbcfca2.png">
这个sort暂时删除，我看后端接口有做order weight，这里sort由于未指定内部规则导致浏览器sort结果不同

![image](https://user-images.githubusercontent.com/36620969/202330834-211bbad4-2c55-4afd-a5f5-b268d5c0125b.png)
这里删除比如weight是1 2 3 4 5删除3的话导致weight不连续，修改为删除3，判断weight>3的要做weight-1然后update

提了push的bugfix/chartgroup-move

**Comment by jsers** [comment]
合并到了，但是还是建议有时间升级到新版本

**Comment by wjyzhixing** [comment]
新版本是不是就把上移下移这些去掉了，重构了下这个detail

**Comment by jsers** [comment]
是的，大盘详情整体重构了，去掉了上下移动，分组和图表卡片都可拖动重新布局，图表也可夸分组移动

Jingyu Wang ***@***.***> 于2022年11月17日周四 12:01写道：
