### ISSUE TITLE
菜单展开建议

### ISSUE THREAD

**Issue by JellyZero** [n9e/fe-v5#214]
![image](https://user-images.githubusercontent.com/109566229/203536923-83d76981-0685-4d83-b4e4-c0f47a2a398c.png)

目前这个菜单规则是鼠标移动上去就展开，有点影响使用，移动快了看着很凌乱，建议点击展开或者移动延迟一段时间展开

**Comment by guguji5** [comment]
收到，我们尝试加个配置，让开发者自己选择hover和click来触发菜单。

**Comment by JellyZero** [comment]
good

**Comment by guguji5** [comment]
https://user-images.githubusercontent.com/17986248/204459172-1e7fd4b3-ed5e-473d-84ef-9b2e87e763e6.mp4

增加了`activeMode`参数，现在默认还是hover，可以手动改成click。

效果如上图。目前全展开模式下可以打开多个菜单，而收起状态下只有一个菜单可以打开（参考的ant design）

**Comment by bytew021** [comment]
可以加个选择不， 我想回到旧版菜单~~

**Comment by guguji5** [comment]
> 可以加个选择不， 我想回到旧版菜单~~

我们把默认打开菜单的交互从hover 改成click，交互上和旧版菜单就一样了。坐等下一个版本，或者拉最新代码试一试吧
