### ISSUE TITLE
左侧菜单 显示权限问题

### ISSUE THREAD

**Issue by bbaobelief** [n9e/fe-v5#217]
前端版本：5.14.2
后端版本：v5.14.2-f8ac0a9b4ad9657b71b34a200b42a80e474d71d6

普通用户没有 **系统信息**子菜单权限，但还显示 **系统信息** 菜单，5.14之前版本没问题。
![image](https://user-images.githubusercontent.com/3918461/203685341-214c2492-0d6e-4a84-a4f3-222bd8436731.png)

**Comment by guguji5** [comment]
![image](https://user-images.githubusercontent.com/17986248/204419147-7a1d2dfd-8ea9-451f-8164-6858355824f7.png)
guest用户展示系统信息，但是里边也只有【系统版本】一个菜单吧

**Comment by bbaobelief** [comment]
我是自定义了角色，你把guest用户/help/version(系统版本)权限删除，还会显示根菜单-系统信息。
以前版本如果没有/help/version权限，根菜单-系统信息是不显示的，现在会显示一个空菜单
