### ISSUE TITLE
如何将监控对象默认为自定义的业务组

### ISSUE THREAD

**Issue by chenchanglei** [n9e/fe-v5#221]
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/13267570/206620951-aa9a4882-42cf-4b25-aeec-505b4c47e487.png">

**Comment by chenchanglei** [comment]
前端版本：5.14.1
后端版本：v5.14.0-da5dd683d684901389336f96c55ae58837b9230e

**Comment by UlricQin** [comment]
目前还不提供这个机制，需要自己写脚本、程序调用夜莺的接口来完成，或者直接操作夜莺的DB也行

**Comment by chenchanglei** [comment]
操作DB是改哪里

**Comment by UlricQin** [comment]
target表

**Comment by chenchanglei** [comment]
感谢
