### ISSUE TITLE
/api/n9e/board/1/pure接口在频繁调用

### ISSUE THREAD

**Issue by chenchanglei** [n9e/fe-v5#222]
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/13267570/206686755-c4d6feeb-e276-4c02-a587-936763e4ea73.png">

**Comment by chenchanglei** [comment]
调用的主要意义是什么？
前端版本：5.14.1
后端版本：v5.14.0-da5dd683d684901389336f96c55ae58837b9230e

**Comment by jsers** [comment]
这是大盘版本监听接口，以防止多人编辑同一个大盘可能互相覆盖

MiraClei ***@***.***> 于2022年12月9日周五 19:03写道：

**Comment by chenchanglei** [comment]
频率可以调整吗？

**Comment by jsers** [comment]
目前还不支持调整

MiraClei ***@***.***> 于2022年12月9日周五 20:16写道：

**Comment by chenchanglei** [comment]
ok
