### ISSUE TITLE
告警匿名访问的方式是什么

### ISSUE THREAD

**Issue by chenchanglei** [n9e/fe-v5#223]
修改webapi.conf 配置后，访问什么地址可以看到告警信息
已修改为：AlertDetail = true
前端版本：5.14.1
后端版本：v5.14.0-da5dd683d684901389336f96c55ae58837b9230e

**Comment by chenchanglei** [comment]
http://ip:port/alert-cur-events
尝试以如上方式访问，仍需要登录

**Comment by jsers** [comment]
目前没有告警事件匿名访问模式

MiraClei ***@***.***> 于2022年12月9日周五 19:13写道：

**Comment by chenchanglei** [comment]
AlertDetail = true
好的，这项的主要作用是什么？

**Comment by UlricQin** [comment]
这是控制告警详情页面

**Comment by chenchanglei** [comment]
👌
