### ISSUE TITLE
蜂窝图绿色代表什么，看起来是一组里最大的数字会变成绿色，可以添加自定义颜色吗？

### ISSUE THREAD

**Issue by chenchanglei** [n9e/fe-v5#227]
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/13267570/209495136-961e5d4b-e8ea-4a45-958b-08caf061a6b1.png">
<img width="1540" alt="image" src="https://user-images.githubusercontent.com/13267570/209495149-9f584891-8fc1-4ef2-a8de-d71aa93bc885.png">

**Comment by jsers** [comment]
在图表样式里面有颜色的设置，内置了几组颜色方案，每组颜色都是通过三个颜色组成，默认是 绿色 -> 灰色 -> 橙色，映射数据是从 max ->
min，还有也可以反转颜色
暂时不支持自定义颜色

MiraClei ***@***.***> 于2022年12月26日周一 11:13写道：

**Comment by chenchanglei** [comment]
👌
