### ISSUE TITLE
无法取消已勾选的业务组

### ISSUE THREAD

**Issue by liuxin638507** [n9e/fe-v5#230]
首次登录系统能看到所有主机信息，选择某一个后无法取消已选择的业务组，再次点击还是当前业务组，导致查看不了所有节点信息
![d0c2732f3525443f0822afaaae7582b](https://user-images.githubusercontent.com/32058132/211286433-799255b6-6027-4ee4-b5b0-495397e0b6fe.png)

**Comment by jsers** [comment]
v5.15.0 已修复
