### ISSUE TITLE
监控大盘-编辑图表-关联数据源 选中之后无法清除

### ISSUE THREAD

**Issue by bbaobelief** [n9e/fe-v5#233]
前端版本：5.14.2
后端版本：v5.14.2-f8ac0a9b4ad9657b71b34a200b42a80e474d71d6

关联数据源 选中之后无法清除，影响全局集群切换看图
![image](https://user-images.githubusercontent.com/3918461/211757140-590d75c3-feaf-47a4-902f-d632b22f3911.png)

**Comment by jsers** [comment]
v5.15.0 已修复
