### ISSUE TITLE
即时查询的Graph标签页下方的Series列表展示不全

### ISSUE THREAD

**Issue by gengleiming** [n9e/fe-v5#240]
前端版本：v5.14.3
后端版本：v5.14.4

实际查询出6条数据，而下方的Series表格中只能滚动显示5条数据，有一条数据被遮挡住了。
![企业微信截图_16740236092350](https://user-images.githubusercontent.com/11794884/213101056-7154b07e-7b97-4aae-975f-e578229be5bd.png)

![image](https://user-images.githubusercontent.com/11794884/213102050-e74c6adf-00eb-4f45-9e57-0b98b6e6270a.png)

**Comment by jsers** [comment]
下个版本会修复这个问题

gengleiming ***@***.***> 于2023年1月18日周三 14:31写道：

**Comment by jicki** [comment]
@gengleiming 疑，请问如何使用 白色主题

**Comment by gengleiming** [comment]
> @gengleiming 疑，请问如何使用 白色主题

你是说左侧菜单栏的样式吗？左侧菜单栏我回退到旧版本的样式了

**Comment by jicki** [comment]
> > @gengleiming 疑，请问如何使用 白色主题
> 
> 你是说左侧菜单栏的样式吗？左侧菜单栏我回退到旧版本的样式了

呃 为什么呢，白色不好看吗？ 怎么可以切换到白色的 样式呢

**Comment by gengleiming** [comment]
> > > @gengleiming 疑，请问如何使用 白色主题
> > 
> > 
> > 你是说左侧菜单栏的样式吗？左侧菜单栏我回退到旧版本的样式了
> 
> 呃 为什么呢，白色不好看吗？ 怎么可以切换到白色的 样式呢

就是因为白色好用，所以我把菜单栏回退到了旧版本了呀，上面截图是已经回退到旧版本的示例

**Comment by jicki** [comment]
> > > > @gengleiming 疑，请问如何使用 白色主题
> > > 
> > > 
> > > 你是说左侧菜单栏的样式吗？左侧菜单栏我回退到旧版本的样式了
> > 
> > 
> > 呃 为什么呢，白色不好看吗？ 怎么可以切换到白色的 样式呢
> 
> 就是因为白色好用，所以我把菜单栏回退到了旧版本了呀，上面截图是已经回退到旧版本的示例

多少版本的是～白色的？

**Comment by gengleiming** [comment]
> > > > > @gengleiming 疑，请问如何使用 白色主题
> > > > 
> > > > 
> > > > 你是说左侧菜单栏的样式吗？左侧菜单栏我回退到旧版本的样式了
> > > 
> > > 
> > > 呃 为什么呢，白色不好看吗？ 怎么可以切换到白色的 样式呢
> > 
> > 
> > 就是因为白色好用，所以我把菜单栏回退到了旧版本了呀，上面截图是已经回退到旧版本的示例
> 
> 多少版本的是～白色的？

看下 issue #214

**Comment by jsers** [comment]
v5.15.0 已修复
