### ISSUE TITLE
图表 bug

### ISSUE THREAD

**Issue by JellyZero** [n9e/fe-v5#252]
<img width="305" alt="image" src="https://user-images.githubusercontent.com/109566229/217419303-744a99b6-bf37-407a-aac5-f2187114da62.png">

**Comment by jsers** [comment]
看下图表的阈值配置

JeffreyBool ***@***.***> 于2023年2月8日周三 11:13写道：

**Comment by JellyZero** [comment]
没事了，grafana 导入的默认有个空的阈值导致

**Comment by JellyZero** [comment]
<img width="467" alt="image" src="https://user-images.githubusercontent.com/109566229/217517797-cf2477e2-5d6b-43c9-ae4b-392e8bd47188.png">
这个选择res 选择了下次进入能自动选择吗

**Comment by jsers** [comment]
可以，下个版本带上

JeffreyBool ***@***.***> 于2023年2月8日周三 19:31写道：
