### ISSUE TITLE
前端项目源码编译环境问题

### ISSUE THREAD

**Issue by nanhai-13** [n9e/fe-v5#255]
前端源码项目安装编译环境不匹配
 GitHub源码地址：https://github.com/n9e/fe-v5
 版本：v5.15.0

1：环境安装依赖版本不匹配
Dependencies 
node: v16.13.0
npm: 8.1.0

2：npm install 无法安装
[package.json](https://github.com/n9e/fe-v5/blob/master/package.json) 文件中reactjs相关的包的版本很多都不匹配。

**Comment by guguji5** [comment]
你最新的commit id 发一下

**Comment by guguji5** [comment]
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/17986248/219828265-c1bb51af-e169-476b-af5c-04f4401294bf.png">
w我试了下master代码，编译没问题的

**Comment by nanhai-13** [comment]
![image](https://user-images.githubusercontent.com/88566435/219849829-f124a8be-e55c-452b-8b9b-15141b0a7e49.png)

**Comment by nanhai-13** [comment]
要求npm v9.5.0版本；升级后就是这个样子的。

**Comment by guguji5** [comment]
@nanhai-13 复现了
<img width="672" alt="image" src="https://user-images.githubusercontent.com/17986248/219853258-f7d1d199-9fd2-4958-8a76-2c84fbe84ffa.png">
