### ISSUE TITLE
utils内sizeFormatter函数的convertNum参数默认值错误

### ISSUE THREAD

**Issue by zhangtinghang** [n9e/fe-v5#264]
utils下sizeFormatter 函数内，若不传convertNum，则默认值为2024，其中赋予默认值中。
`convertNum: 1024 | 1000`
会默认按位或，导致最终计算值不准确。

**Comment by guguji5** [comment]
@zhangtinghang 有没有兴趣提个PR？

**Comment by UlricQin** [comment]
在 v6 下搞吧，v6的前端是 github.com/n9e/fe ，v5 版本已经在 2023.7.29 结束社区support了

**Comment by jsers** [comment]
https://github.com/n9e/fe-v5/pull/265
v6 版本没这个问题，v5 已经提过 PR 解决了
