### ISSUE TITLE
左侧菜单，打开2个一级菜单时， 有滚动条显示不友好

### ISSUE THREAD

**Issue by wushanru** [n9e/fe-v5#68]
1、服务端用的：5.0.0-ga-04
2、前端版本用的：5.0.0-ga-02
3、服务部署在centos7上面
4、在windows上访问的，用的google浏览器，电脑显示分辨率为2560*1600，更改文本、应用等项目大小200%，联想小新pro
![image](https://user-images.githubusercontent.com/60475921/145345530-a46f7950-a2fb-4448-8b41-58f44efedfa5.png)

**Comment by guguji5** [comment]
@wushanru 试一下 https://github.com/n9e/fe-v5/releases/tag/5.0.0-ga-03 。优化了一下
