### ISSUE TITLE
【监控大盘】详情页面优化图表展示效果

### ISSUE THREAD

**Issue by UlricQin** [n9e/fe-v5#70]
![image](https://user-images.githubusercontent.com/2769466/146126650-26abc677-717e-4847-88d9-df96345feafe.png)

**Comment by UlricQin** [comment]
这个组件可能在多个地方使用，可以通过某个属性控制一下展示方式，在监控大盘页面，就用下拉菜单，在对象视角页面就平铺icon

**Comment by jsers** [comment]
v5.1.7 版本新增图表已优化标题栏，之前的版本目前暂不考虑优化
