### ISSUE TITLE
大盘value format 建议增加自定义公式展示

### ISSUE THREAD

**Issue by JeffreyBool** [n9e/fe-v5#76]
![image](https://user-images.githubusercontent.com/24415888/147083835-dec372e9-b9a6-462c-85f4-637d3b52e724.png)

最好能自定义公式展示，和 grafana 差不多，比如还有保留小数位数展示

**Comment by jsers** [comment]
这块在计划中了

JeffreyBool ***@***.***> 于2021年12月22日周三 19:11写道：

**Comment by jsers** [comment]
@JeffreyBool 
v5.1.7 版本已支持
![image](https://user-images.githubusercontent.com/7424634/160777409-4c21e79e-459d-4d4f-b5c6-caea30b7a52b.png)
