### ISSUE TITLE
大盘变量关联引用

### ISSUE THREAD

**Issue by bbaobelief** [n9e/fe-v5#82]
希望大盘变量可以相互引用。比如 a变量的值可以给b变量用
![image](https://user-images.githubusercontent.com/3918461/150058733-b2f08f90-aae4-484e-b1e1-c213aae298ac.png)

**Comment by guguji5** [comment]
哇，优化的时候考虑一下

**Comment by UlricQin** [comment]
变量定义里可以引用上一个变量，筛值正则不 支持引用

**Comment by guguji5** [comment]
正则里边不允许变量替换，容易跟原生正则混淆
