### ISSUE TITLE
监控指标图表缩小后不显示指标名称

### ISSUE THREAD

**Issue by zhangzheming629** [n9e/fe-v5#85]
前端版本:5.1.3
监控指标图表缩小后不显示指标名称
![1645068588(1)](https://user-images.githubusercontent.com/38377736/154399694-010bdfac-aa5a-4fe5-b448-723ad722c8b1.png)

**Comment by UlricQin** [comment]
使用最新版本的Chrome进行测试。

**Comment by zhangzheming629** [comment]
你的chrome版本是多少呀，我试了chrome的Version 98.0.4758.102 (Official Build) (64-bit)这个版本还是有这个问题

**Comment by guguji5** [comment]
与https://github.com/n9e/fe-v5/issues/70 重复

**Comment by guguji5** [comment]
@zhangzheming629 改了，可以先自己build用，或者等下次release
