### ISSUE TITLE
监控大盘图标分组上移下移功能错误

### ISSUE THREAD

**Issue by zhangzheming629** [n9e/fe-v5#86]
前端版本:5.1.3
监控大盘图标分组上移下移功能错误(上移是下移，下移是上移)
![1645068695(1)](https://user-images.githubusercontent.com/38377736/154399903-c459e498-b200-4381-b375-27a82c6fd270.png)

**Comment by UlricQin** [comment]
你用的什么浏览器，我用最新版本的chrome测试没问题

**Comment by zhangzheming629** [comment]
> 你用的什么浏览器，我用最新版本的chrome测试没问题，还有别人遇到这个问题么？可以在这个帖子里回复



> 你用的什么浏览器，我用最新版本的chrome测试没问题，还有别人遇到这个问题么？可以在这个帖子里回复
Firefox Browser 91.4.lesr
![image](https://user-images.githubusercontent.com/38377736/154440959-ac4aef3a-5223-4cd9-9d93-395c5326b20d.png)

**Comment by UlricQin** [comment]
夜莺只支持chrome

**Comment by zhangzheming629** [comment]
好的

**Comment by zhangzheming629** [comment]
使用chrome正常
