### ISSUE TITLE
自定义头像保存时， 自定义头像url 类型错误  TypeError:Failed to fetch

### ISSUE THREAD

**Issue by pylixm** [n9e/fe-v5#88]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/15826317/154601108-c5bd19ec-a971-4127-ad8d-8468ef23953d.png">

**Comment by guguji5** [comment]
这并不是一个可访问的图片地址，可以把url放到浏览器里打开试试

<img width="919" alt="image" src="https://user-images.githubusercontent.com/17986248/155252520-d0b5cfe4-b8eb-490e-9b93-33332b1dc31b.png">

**Comment by pylixm** [comment]
https://gitee.com/pylixm/picture/raw/master/2022-2-18/1645148006470-WechatIMG2.jpeg

**Comment by guguji5** [comment]
@pylixm 感谢反馈，代码已修改并提交，可以先自己build，或者等下一个release
