### ISSUE TITLE
监控大盘增加自动刷新

### ISSUE THREAD

**Issue by bbaobelief** [n9e/fe-v5#89]
期待监控大盘增加自动刷新功能。如grafana
![image](https://user-images.githubusercontent.com/3918461/155443692-bb2e0e38-ba80-46ea-b068-4684e115607a.png)

**Comment by jsers** [comment]
@bbaobelief 
v5.1.7 版本已支持
![image](https://user-images.githubusercontent.com/7424634/160777637-3d08ab84-dc9e-404a-9b16-e137d958fc9d.png)
